#!/bin/bash

#This is the final set of commands that worked:

ml purge
ml python/2.7.11
ml intel/17.4 impi/17.3 mkl/17.3
ml fftw/3.3.4 jpeg/9b cmake/3.14.1 zlib/1.2.11

export LV=29Oct20
export INSTALLDIR=/curc/sw/lammps/$LV/impi/17.3/intel/17.4
mkdir -p $INSTALLDIR

git clone -b stable https://github.com/lammps/lammps.git lammps-$LV

cd lammps-$LV
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$INSTALLDIR -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="-O3 -DNDEBUG -axCORE-AVX512,CORE-AVX2,AVX,SSE4.2" -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG -axCORE-AVX512,CORE-AVX2,AVX,SSE4.2" BUILD_MPI=on BUILD_OMP=on -DPKG_USER-INTEL=on INTEL_ARCH=cpu FFTW3_INCLUDE_DIRS=$CURC_FFTW_INC FFTW3_LIBRARIES=$CURC_FFTW_LIB WITH_JPEG=yes JPEG_INCLUDE_DIR=$CURC_JPEG_INC JPEG_LIBRARIES=$CURC_JPEG_LIB -DPKG_ASPHERE=ON -DPKG_BODY=ON -DPKG_CLASS2=ON -DPKG_COLLOID=ON -DPKG_COMPRESS=ON -DPKG_CORESHELL=ON -DPKG_DIPOLE=ON -DPKG_GPU=OFF -DPKG_GRANULAR=ON -DPKG_KIM=on -DPKG_KOKKOS=on -DPKG_KSPACE=on -DPKG_LATTE=OFF -DPKG_MANYBODY=on -DPKG_MC=ON -DPKG_MESSAGE=OFF -DPKG_MISC=ON -DPKG_MLIAP=OFF -DPKG_MOLECULE=ON -DPKG_MPIIO=OFF -DPKG_MSCG=OFF -DPKG_OPT=on -DPKG_PERI=ON -DPKG_POEMS=on -DPKG_PYTHON=ON -DPKG_QEQ=ON -DPKG_REPLICA=on -DPKG_RIGID=ON -DPKG_SHOCK=ON -DPKG_SNAP=ON -DPKG_SPIN=OFF -DPKG_SRD=ON -DPKG_USER-ADIOS=OFF -DPKG_USER-ATC=on -DPKG_USER-AWPMD=on -DPKG_USER-BOCS=OFF -DPKG_USER-CGDNA=OFF -DPKG_USER-CGSDK=OFF -DPKG_USER-COLVARS=on -DPKG_USER-DIFFRACTION=OFF -DPKG_USER-DPD=OFF -DPKG_USER-DRUDE=OFF -DPKG_USER-EFF=OFF -DPKG_USER-FEP=on -DPKG_USER-H5MD=OFF -DPKG_USER-INTEL=on -DPKG_USER-LB=OFF -DPKG_USER-MANIFOLD=OFF -DPKG_USER-MEAMC=ON -DPKG_USER-MESODPD=OFF -DPKG_USER-MESONT=OFF -DPKG_USER-MGPT=OFF -DPKG_USER-MISC=on -DPKG_USER-MOFFF=OFF -DPKG_USER-MOLFILE=OFF -DPKG_USER-NETCDF=OFF -DPKG_USER-OMP=ON -DPKG_USER-PHONON=on -DPKG_USER-PLUMED=OFF -DPKG_USER-PTM=OFF -DPKG_USER-QMMM=OFF -DPKG_USER-QTB=OFF -DPKG_USER-QUIP=OFF -DPKG_USER-REACTION=OFF -DPKG_USER-REAXC=ON -DPKG_USER-SCAFACOS=OFF -DPKG_USER-SDPD=OFF -DPKG_USER-SMD=on -DPKG_USER-SMTBQ=OFF -DPKG_USER-SPH=OFF -DPKG_USER-TALLY=OFF -DPKG_USER-UEF=OFF -DPKG_USER-VTK=OFF -DPKG_USER-YAFF=OFF -DPKG_VORONOI=ON ../cmake

make -j 12
make install

